version: "3.5"
services:
  erigon:
    build:
      context: erigon
      args:
        UPSTREAM_VERSION: v3.0.5
        STAKER_SCRIPTS_VERSION: v0.1.2
        DATA_DIR: /home/erigon/.local/share
    environment:
      EXTRA_OPTS: "--http.api=engine,eth,erigon,web3,net,debug,trace,txpool"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  data: {}
