version: "3.5"
services:
  erigon:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 30405
    ports:
      - "30405:30405/tcp"
      - "30405:30405/udp"
    image: "erigon.erigon.dnp.dappnode.eth:0.1.43"

