version: "3.5"
services:
  erigon:
    build:
      args:
        NETWORK: holesky
        P2P_PORT: 30406
    ports:
      - "30406:30406/tcp"
      - "30406:30406/udp"
    volumes:
      - data:/home/erigon/.local/share
