name: Build test
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ipfs-dev-gateway
    steps:
      - uses: actions/checkout@v4
      - run: npx @dappnode/dappnodesdk github-action build --skip-save --variant mainnet --content_provider=http://10.200.200.7:5001 --eth_provider=https://web3.dappnode.net
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
