name: Release

on:
  workflow_dispatch:
    inputs:
      consensus_client:
        description: "Consensus Client"
        required: true
        type: choice
        options: [lodestar, teku, prysm, nimbus, lighthouse]
      skip_tests:
        description: "Skip tests and publish directly after build"
        required: false
        type: boolean
        default: false
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  release:
    uses: dappnode/workflows/.github/workflows/staking-release.yml@master
    with:
      package_variant: "hoodi"
      consensus_client: ${{ inputs.consensus_client || '' }}
      skip_tests: ${{ inputs.skip_tests || false }}
    secrets: inherit
